config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'addresses#index'
  resources :addresses, only: [:index, :new, :create] do
    collection do
      delete :destroy_all
      get :export
    end
  end
end

app/models/address.rb
require 'open-uri'

class Address < ActiveRecord::Base
  include Concerns::FirstScrapper
  include Concerns::SecondScrapper
  # include Concerns::ToXls

  # validation
  validates :full_name, presence: true
  validates :full_address, presence: true


  def self.to_csv
    CSV.generate do |csv|
      columns = ["full_name", "full_address", "phone_number"]
      csv << columns

      all.each do |address|
        csv << address.attributes.values_at(*columns)
      end
    end
  end
end


# Translation
# 1. annuaire -> Phone Book
# 2. chercher -> look for
# 3. les      -> the
# 4. ou       -> OR
# 5. quoi qui => watch Who

app/models/concerns/first_scrapper.rb
module Concerns::FirstScrapper
  extend ActiveSupport::Concern

  def scrap_and_update_information_process_1
    base_url    = "http://www.pagesjaunes.fr/trouverlesprofessionnels/rechercheClassique.do"
    success = true

    response = HTTParty.post(base_url, query: { quoiqui: self.full_name, ou: self.full_address })
    data     = Nokogiri::HTML(response)


    results  = data.css("ol li.visitCard")

    unless results.blank? && results.count <= 0
      results.each do |result|
        id = result["id"]
        full_name     = scrap_full_name_1(data, id)
        full_address  = scrap_full_address_1(data, id)
        phone_number  = scrap_phone_number_1(data, id)

        unless full_name.blank? && full_address.blank? && phone_number.blank?
          address = Address.new(full_name: full_name, full_address: full_address, phone_number: phone_number)
          address.save!(validate: false)
        end
      end
    else
      success = false
    end
  end

  def scrap_full_address_1(data, id)
    result = data.css("li##{id} .visitCardContent .dataCard .localisationBlock p")

    return result.text rescue nil
  end


  def scrap_full_name_1(data, id)
    result = data.css("li##{id} .visitCardContent h2.titleMain a.companyName span")

    return result.first.text rescue nil
  end


  def scrap_phone_number_1(data, id)
    skip_text = "Signification des pictogrammes."
    skip_text2 = "Signification des pictogrammes"

    result = data.css("li##{id} .visitCardContent .dataCard .contactBlock  ul.blocPhoneNumber li.hideTel")
    result = result.first.css("strong").text rescue nil

    return result.gsub(skip_text, "").gsub(skip_text2, "")
  end
end

app/models/concerns/second_scrapper.rb
module Concerns::SecondScrapper
  extend ActiveSupport::Concern

  # The Day I started scrapping information from this site
  # It was using get request to fetch information
  # When I was done scrapping data, it was changed to POST request
  # and also they changed the layout completely
  def scrap_and_update_information_process_2
    base_url    = "http://www.pagesjaunes.fr/annuaire/chercherlespros?quoiqui=#{self.full_name}&ou=#{self.full_address}&idOu=''"
    success = true
    
    response  = HTTParty.get(base_url)
    data      = Nokogiri::HTML(response)

    result_container  = data.css("section#listResults.results")
    p result_container

    unless result_container.blank?
      articles = result_container.css("article.bi-bloc")

      if articles.count > 0
        articles.each do |article|
          id = article["id"]

          full_address  = scrap_full_address(data, id)
          full_name     = scrap_full_name(data, id)
          phone_number  = scrap_phone_number(data, id)

          unless full_name.blank? || full_address.blank? || phone_number.blank?
            address = Address.new(full_name: full_name, full_address: full_address, phone_number: phone_number)
            address.save!(validate: false)
          end
        end
      else
        success = false
      end
    else
      success = false
    end

    return success
  end

  def scrap_full_address(data, id)
    result        = data.css("article##{id} header.v-card .row .adresse-container a p span")
    full_address  = ""

    result.each do |res|
      full_address += res.text unless res.blank?
    end

    return full_address
  end

  def scrap_full_name(data, id)
    result    = data.css("article##{id} div.description div.activites-cris span.donnees-insee span")

    name = result.map { |res| res.text }
    return name.join(" ")
  end

  def scrap_phone_number(data, id)
    result = data.css("article##{id} footer.bi-contact li.item strong")
    phone = ""

    if result.present?
      if result.is_a?(Array)
        phones = result.map { |ph| ph.text }
        phone = phones.join(", ")
      else
        phone = result.text
      end
    end

    return phone
  end
end

app/models/concerns/to_xls.rb
module Concerns::ToXls
  extend ActiveSupport::Concern

  def export_to_xls
    
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:destroy]

  # GET /addresses
  def index
    @addresses = Address.all.page(params[:page])
  end

  def export
    @addresses = Address.all

    respond_to do |format|
      format.html
      format.csv { send_data @addresses.to_csv }
      format.xls
    end
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # POST /addresses
  def create
    @address = Address.new(address_params)

    if @address.valid?
      if @address.scrap_and_update_information_process_1 ||
         @address.scrap_and_update_information_process_2
        p "scrap_and_update_information_process_1"
        gflash success: 'Address was successfully created.'
        redirect_to root_path
      else
        gflash error: 'Unable to scrap data'
        redirect_to root_path
      end
    else
      gflash :now, :error => @address.errors.full_messages.join("<br/>").html_safe
      render :new
    end
  end

  def destroy_all
    Address.destroy_all
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def address_params
      params.require(:address).permit(:full_name, :full_address)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/index.html.erb
<div class="col-md-12">
  <div class="panel panel-info">
    <div class="panel-heading clearfix">
      <h4 class="panel-title pull-left" style="padding-top: 7.5px;">
        <strong><%= pluralize Address.count, "Record" %></strong>
      </h4>

      <div class="btn-group pull-right">
        <%= link_to "<i class='glyphicon glyphicon-save'></i> Export To Excel".html_safe, export_addresses_path(format: 'xls'), class: 'btn btn-sm btn-success pull-right' %>

        <%= link_to "<i class='glyphicon glyphicon-save'></i> Export To Csv".html_safe, export_addresses_path(format: 'csv'), class: 'btn btn-sm btn-info pull-right' %>
        
        <%= link_to "<i class='glyphicon glyphicon-trash'></i> Clear All Data".html_safe, destroy_all_addresses_path, method: :delete, data: { confirm: 'Are you sure to clear database?' }, class: 'btn btn-sm btn-danger pull-right' %>
        
        <%= link_to "<i class='glyphicon glyphicon-plus'></i> New Address".html_safe, new_address_path,  class: 'btn btn-sm btn-primary pull-right' %>
      </div>      
    </div>      

    <div class="panel-body">
      <table class="table">
        <thead>
          <tr>
            <th>Full name</th>
            <th>Full address</th>
            <th>Phone number</th>
          </tr>
        </thead>

        <tbody>
          <% @addresses.each do |address| %>
            <tr>
              <td><%= address.full_name %></td>
              <td><%= address.full_address %></td>
              <td><%= address.phone_number %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="panel-footer">
      <%= paginate @addresses, theme: 'twitter-bootstrap-3' %>
    </div>

  </div>
</div>

app/views/addresses/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Full Name</Data></Cell>
        <Cell><Data ss:Type="String">Full Address</Data></Cell>
        <Cell><Data ss:Type="String">Phone</Data></Cell>
      </Row>
    <% @addresses.each do |address| %>
      <Row>
        <Cell><Data ss:Type="String"><%= address.full_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= address.full_address %></Data></Cell>
        <Cell><Data ss:Type="String"><%= address.phone_number %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/addresses/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Scrapp</h3>
    </div>

    <%= simple_form_for @address do |f| %>
      <div class="panel-body">
        <div class="input-group">
          <%= f.text_field :full_name, class: 'form-control input-lg', placeholder: 'name', required: true %>
          <span class="input-group-addon glyphicon glyphicon-user"></span>
        </div>
        <br/>

        <div class="input-group">
          <%= f.text_field :full_address, class: 'form-control input-lg', placeholder: 'city', label: false, required: true %>
          <span class="input-group-addon glyphicon glyphicon-globe"></span>
        </div>
      </div>  

      <div class="panel-footer">
        <%= f.submit 'Scrap Data', class: 'btn btn-sm btn-primary' %>
        <%= link_to 'List Data', addresses_path, class: 'btn btn-sm btn-primary' %>
      </div>
    <% end %>    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Scrap French Orgination Information</title>
    
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <header>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- brand -->
          <div class="navbar-header">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to 'Scrapper', root_path, class: 'navbar-brand' %>
            </div>
          </div>
          <!-- /brand -->
          
          <!-- right elements -->
          <div class="collapse navbar-collapse" id="registration-navbar">
            <ul class="nav navbar-nav navbar-right">
              <li>
                <% if current_user %>
                  <%= link_to "Hello Admin, Logout?", destroy_user_session_path, method: :delete, class: 'btn btn-sm btn-primary' %>
                <% else %>
                  <%= link_to "Login", new_user_session_path, class: 'btn btn-sm btn-primary' %>
                <% end %>
              </li>
            </ul>
          </div>
          <!-- /right elements -->
        </div>
      </nav>
    </header>

    <div class="container">
      <div class="row">
        <%= yield %>
        <%= gflash %>
      </div>
    </div>
  </body>
</html>